sqlserver.url=jdbc:sqlserver://localhost:1433;databaseName=GuateCompras;encrypt=true;trustServerCertificate=true
sqlserver.user=usuario_aplicacion
sqlserver.password=CAMBIAR_LOCALMENTE
postgres.url=jdbc:postgresql://localhost:5432/GuateCompras
postgres.user=usuario_aplicacion
postgres.password=CAMBIAR_LOCALMENTE
