CREATE TABLE Sucursal (
    id_sucursal      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_sucursal  VARCHAR(10)  NOT NULL UNIQUE,
    direccion        VARCHAR(150) NOT NULL,
    ciudad           VARCHAR(60)  NOT NULL,
    region           VARCHAR(60)  NOT NULL,
    telefono         VARCHAR(20)  NOT NULL
);

CREATE TABLE Departamento (
    id_departamento  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sucursal      INT          NOT NULL REFERENCES Sucursal(id_sucursal),
    nombre           VARCHAR(60)  NOT NULL,
    descripcion      VARCHAR(200) NULL,
    CONSTRAINT UQ_Departamento_SucursalNombre UNIQUE (id_sucursal, nombre)
);

CREATE TABLE Articulo (
    id_articulo     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_articulo VARCHAR(20)  NOT NULL UNIQUE,
    nombre          VARCHAR(100) NOT NULL,
    descripcion     VARCHAR(300) NULL
);

CREATE TABLE Proveedor (
    id_proveedor     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_proveedor VARCHAR(20)  NOT NULL UNIQUE,
    nombre_comercial VARCHAR(100) NOT NULL,
    direccion        VARCHAR(150) NOT NULL,
    telefono         VARCHAR(20)  NOT NULL,
    categoria        VARCHAR(80)  NOT NULL
);

CREATE TABLE ProveedorArticulo (
    id_proveedor INT           NOT NULL REFERENCES Proveedor(id_proveedor),
    id_articulo  INT           NOT NULL REFERENCES Articulo(id_articulo),
    precio       DECIMAL(10,2) NOT NULL CHECK (precio > 0),
    CONSTRAINT PK_ProveedorArticulo PRIMARY KEY (id_proveedor, id_articulo)
);

CREATE TABLE RelacionComercial (
    id_relacion_comercial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor_a INT NOT NULL REFERENCES Proveedor(id_proveedor),
    id_proveedor_b INT NOT NULL REFERENCES Proveedor(id_proveedor),
    CONSTRAINT CK_RelacionComercial_Distintos CHECK (id_proveedor_a <> id_proveedor_b),
    CONSTRAINT UQ_RelacionComercial_Par UNIQUE (id_proveedor_a, id_proveedor_b)
);

CREATE TABLE TipoOrden (
    id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(20) NOT NULL UNIQUE CHECK (nombre IN ('Grande','Chica'))
);

CREATE TABLE SubtipoOrden (
    id_subtipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo    INT         NOT NULL REFERENCES TipoOrden(id_tipo),
    nombre     VARCHAR(20) NOT NULL CHECK (nombre IN ('Urgente','Normal'))
);

CREATE TABLE OrdenCompra (
    id_orden            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion         VARCHAR(200) NOT NULL,
    fecha_creacion      DATE NOT NULL,
    fecha_limite_oferta DATE NOT NULL CHECK (fecha_limite_oferta >= fecha_creacion),
    id_tipo             INT  NOT NULL REFERENCES TipoOrden(id_tipo),
    id_subtipo          INT  NULL REFERENCES SubtipoOrden(id_subtipo)
);

CREATE TABLE Pedido (
    id_pedido       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INT  NOT NULL REFERENCES Departamento(id_departamento),
    id_orden        INT  NULL REFERENCES OrdenCompra(id_orden),
    id_articulo     INT  NOT NULL REFERENCES Articulo(id_articulo),
    cantidad        INT  NOT NULL CHECK (cantidad > 0),
    fecha_solicitud DATE NOT NULL,
    fecha_necesaria DATE NOT NULL CHECK (fecha_necesaria >= fecha_solicitud)
);

CREATE TABLE Oferta (
    id_oferta       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor    INT NOT NULL REFERENCES Proveedor(id_proveedor),
    id_pedido       INT NOT NULL REFERENCES Pedido(id_pedido),
    precio_unitario DECIMAL(10,2) NOT NULL CHECK (precio_unitario > 0),
    fecha_oferta    DATE NOT NULL
);

CREATE TABLE Adjudicacion (
    id_adjudicacion  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden         INT  NOT NULL UNIQUE REFERENCES OrdenCompra(id_orden),
    fecha_resolucion DATE NOT NULL
);

CREATE TABLE DetalleAdjudicacion (
    id_detalle_adjudicacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_adjudicacion INT NOT NULL REFERENCES Adjudicacion(id_adjudicacion),
    id_pedido       INT NOT NULL REFERENCES Pedido(id_pedido),
    id_oferta       INT NOT NULL REFERENCES Oferta(id_oferta),
    cantidad_final  INT NOT NULL CHECK (cantidad_final > 0),
    precio_acordado DECIMAL(10,2) NOT NULL CHECK (precio_acordado > 0),
    CONSTRAINT UQ_DetalleAdjudicacion_AdjPedido UNIQUE (id_adjudicacion, id_pedido)
);

CREATE TABLE EvaluacionProveedor (
    id_evaluacion           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detalle_adjudicacion INT NOT NULL REFERENCES DetalleAdjudicacion(id_detalle_adjudicacion),
    calificacion            SMALLINT NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario              VARCHAR(300) NULL,
    fecha                   DATE NOT NULL
);

CREATE TABLE Rol (
    id_rol      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol  VARCHAR(40) NOT NULL UNIQUE,
    descripcion VARCHAR(200) NULL
);

CREATE TABLE Pantalla (
    id_pantalla     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_pantalla VARCHAR(60) NOT NULL UNIQUE,
    descripcion     VARCHAR(200) NULL
);

CREATE TABLE Permiso (
    id_rol             INT NOT NULL REFERENCES Rol(id_rol),
    id_pantalla        INT NOT NULL REFERENCES Pantalla(id_pantalla),
    permite_crear      BOOLEAN NOT NULL DEFAULT FALSE,
    permite_leer       BOOLEAN NOT NULL DEFAULT FALSE,
    permite_actualizar BOOLEAN NOT NULL DEFAULT FALSE,
    permite_borrar     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_Permiso PRIMARY KEY (id_rol, id_pantalla)
);

CREATE TABLE Usuario (
    id_usuario      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  VARCHAR(30)  NOT NULL UNIQUE,
    contrasena_hash VARCHAR(255) NOT NULL,
    nombre_completo VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    id_rol          INT NOT NULL REFERENCES Rol(id_rol),
    id_proveedor    INT NULL REFERENCES Proveedor(id_proveedor),
    estado          VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK (estado IN ('Activo','Inactivo')),
    fecha_creacion  DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE OR REPLACE FUNCTION fn_valida_fecha_orden()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.id_orden IS NOT NULL THEN
        IF (SELECT fecha_creacion FROM OrdenCompra WHERE id_orden = NEW.id_orden) < NEW.fecha_solicitud THEN
            RAISE EXCEPTION 'La fecha de creación de la orden no puede ser anterior a la fecha de solicitud del pedido.';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pedido_valida_fecha_orden
AFTER INSERT OR UPDATE ON Pedido
FOR EACH ROW
EXECUTE FUNCTION fn_valida_fecha_orden();

CREATE OR REPLACE FUNCTION fn_valida_fecha_adjudicacion()
RETURNS TRIGGER AS $$
BEGIN
    IF (SELECT fecha_creacion FROM OrdenCompra WHERE id_orden = NEW.id_orden) > NEW.fecha_resolucion THEN
        RAISE EXCEPTION 'La fecha de adjudicación no puede ser anterior a la fecha de creación de la orden.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_adjudicacion_valida_fecha
AFTER INSERT OR UPDATE ON Adjudicacion
FOR EACH ROW
EXECUTE FUNCTION fn_valida_fecha_adjudicacion();