ALTER TABLE OrdenCompra ADD COLUMN IF NOT EXISTS observaciones VARCHAR(300) NULL;
ALTER TABLE Oferta ADD COLUMN IF NOT EXISTS observaciones VARCHAR(300) NULL;
ALTER TABLE Adjudicacion ADD COLUMN IF NOT EXISTS observaciones VARCHAR(300) NULL;
