erDiagram
 ordencompra ||--o{ adjudicacion : "id_orden"
 usuario ||--o{ auditoria : "id_usuario"
 sucursal ||--o{ departamento : "id_sucursal"
 adjudicacion ||--o{ detalleadjudicacion : "id_adjudicacion"
 oferta ||--o{ detalleadjudicacion : "id_oferta"
 pedido ||--o{ detalleadjudicacion : "id_pedido"
 detalleadjudicacion ||--o{ evaluacionproveedor : "id_detalle_adjudicacion"
 pedido ||--o{ oferta : "id_pedido"
 proveedor ||--o{ oferta : "id_proveedor"
 subtipoorden ||--o{ ordencompra : "id_tipo"
 subtipoorden ||--o{ ordencompra : "id_subtipo"
 subtipoorden ||--o{ ordencompra : "id_subtipo"
 tipoorden ||--o{ ordencompra : "id_tipo"
 articulo ||--o{ pedido : "id_articulo"
 departamento ||--o{ pedido : "id_departamento"
 ordencompra ||--o{ pedido : "id_orden"
 pantalla ||--o{ permiso : "id_pantalla"
 rol ||--o{ permiso : "id_rol"
 articulo ||--o{ proveedorarticulo : "id_articulo"
 proveedor ||--o{ proveedorarticulo : "id_proveedor"
 proveedor ||--o{ proveedorrubro : "id_proveedor"
 proveedor ||--o{ relacioncomercial : "id_proveedor_a"
 proveedor ||--o{ relacioncomercial : "id_proveedor_b"
 tipoorden ||--o{ subtipoorden : "id_tipo"
 sucursal ||--o{ sucursaltelefono : "id_sucursal"
 proveedor ||--o{ usuario : "id_proveedor"
 rol ||--o{ usuario : "id_rol"
