erDiagram
 OrdenCompra ||--o{ Adjudicacion : "id_orden"
 Usuario ||--o{ Auditoria : "id_usuario"
 Sucursal ||--o{ Departamento : "id_sucursal"
 Adjudicacion ||--o{ DetalleAdjudicacion : "id_adjudicacion"
 Oferta ||--o{ DetalleAdjudicacion : "id_oferta"
 Pedido ||--o{ DetalleAdjudicacion : "id_pedido"
 DetalleAdjudicacion ||--o{ EvaluacionProveedor : "id_detalle_adjudicacion"
 Pedido ||--o{ Oferta : "id_pedido"
 Proveedor ||--o{ Oferta : "id_proveedor"
 SubtipoOrden ||--o{ OrdenCompra : "id_subtipo"
 SubtipoOrden ||--o{ OrdenCompra : "id_tipo"
 SubtipoOrden ||--o{ OrdenCompra : "id_subtipo"
 TipoOrden ||--o{ OrdenCompra : "id_tipo"
 Articulo ||--o{ Pedido : "id_articulo"
 Departamento ||--o{ Pedido : "id_departamento"
 OrdenCompra ||--o{ Pedido : "id_orden"
 Pantalla ||--o{ Permiso : "id_pantalla"
 Rol ||--o{ Permiso : "id_rol"
 Articulo ||--o{ ProveedorArticulo : "id_articulo"
 Proveedor ||--o{ ProveedorArticulo : "id_proveedor"
 Proveedor ||--o{ ProveedorRubro : "id_proveedor"
 Proveedor ||--o{ RelacionComercial : "id_proveedor_a"
 Proveedor ||--o{ RelacionComercial : "id_proveedor_b"
 TipoOrden ||--o{ SubtipoOrden : "id_tipo"
 Sucursal ||--o{ SucursalTelefono : "id_sucursal"
 Proveedor ||--o{ Usuario : "id_proveedor"
 Rol ||--o{ Usuario : "id_rol"
