CREATE TABLE IF NOT EXISTS SucursalTelefono (id_sucursal INT NOT NULL REFERENCES Sucursal(id_sucursal), telefono VARCHAR(20) NOT NULL, PRIMARY KEY(id_sucursal,telefono));
CREATE TABLE IF NOT EXISTS ProveedorRubro (id_proveedor INT NOT NULL REFERENCES Proveedor(id_proveedor), rubro VARCHAR(80) NOT NULL, PRIMARY KEY(id_proveedor,rubro));
ALTER TABLE Articulo ADD COLUMN IF NOT EXISTS estado VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK(estado IN ('Activo','Inactivo'));
ALTER TABLE Proveedor ADD COLUMN IF NOT EXISTS estado VARCHAR(10) NOT NULL DEFAULT 'Activo' CHECK(estado IN ('Activo','Inactivo'));
CREATE TABLE IF NOT EXISTS Auditoria (id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_usuario INT NULL REFERENCES Usuario(id_usuario), accion VARCHAR(20) NOT NULL, entidad VARCHAR(60) NOT NULL, referencia VARCHAR(80) NULL, fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS IX_Pedido_Orden ON Pedido(id_orden);
CREATE INDEX IF NOT EXISTS IX_Oferta_PedidoProveedor ON Oferta(id_pedido,id_proveedor,fecha_oferta);
CREATE INDEX IF NOT EXISTS IX_Departamento_Sucursal ON Departamento(id_sucursal);
CREATE INDEX IF NOT EXISTS IX_Adjudicacion_Fecha ON Adjudicacion(fecha_resolucion);
CREATE OR REPLACE VIEW vw_OrdenesAbiertas AS SELECT o.id_orden,o.descripcion,o.fecha_creacion,o.fecha_limite_oferta,t.nombre AS tipo,s.nombre AS subtipo FROM OrdenCompra o JOIN TipoOrden t ON t.id_tipo=o.id_tipo LEFT JOIN SubtipoOrden s ON s.id_subtipo=o.id_subtipo WHERE NOT EXISTS(SELECT 1 FROM Adjudicacion a WHERE a.id_orden=o.id_orden) AND o.fecha_limite_oferta>=CURRENT_DATE;
-- @batch
CREATE OR REPLACE FUNCTION validar_oferta_integridad() RETURNS TRIGGER AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM Pedido p JOIN OrdenCompra o ON o.id_orden=p.id_orden JOIN ProveedorArticulo pa ON pa.id_articulo=p.id_articulo AND pa.id_proveedor=NEW.id_proveedor WHERE p.id_pedido=NEW.id_pedido AND NEW.fecha_oferta BETWEEN o.fecha_creacion AND o.fecha_limite_oferta) THEN
 RAISE EXCEPTION 'La oferta requiere pedido asignado, fecha dentro del plazo y artículo en catálogo'; END IF;
 RETURN NEW;
END; $$ LANGUAGE plpgsql;
-- @batch
DROP TRIGGER IF EXISTS tr_Oferta_Integridad ON Oferta;
CREATE TRIGGER tr_Oferta_Integridad BEFORE INSERT OR UPDATE ON Oferta FOR EACH ROW EXECUTE FUNCTION validar_oferta_integridad();
-- @batch
CREATE OR REPLACE FUNCTION validar_detalle_integridad() RETURNS TRIGGER AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM Adjudicacion a JOIN Pedido p ON p.id_orden=a.id_orden JOIN Oferta f ON f.id_pedido=p.id_pedido WHERE a.id_adjudicacion=NEW.id_adjudicacion AND p.id_pedido=NEW.id_pedido AND f.id_oferta=NEW.id_oferta AND f.fecha_oferta<=a.fecha_resolucion AND NEW.cantidad_final<=p.cantidad) THEN
 RAISE EXCEPTION 'La oferta, pedido y adjudicación deben corresponder a la misma orden y cantidad solicitada'; END IF;
 RETURN NEW;
END; $$ LANGUAGE plpgsql;
-- @batch
DROP TRIGGER IF EXISTS tr_DetalleAdjudicacion_Integridad ON DetalleAdjudicacion;
CREATE TRIGGER tr_DetalleAdjudicacion_Integridad BEFORE INSERT OR UPDATE ON DetalleAdjudicacion FOR EACH ROW EXECUTE FUNCTION validar_detalle_integridad();
-- @batch
CREATE OR REPLACE FUNCTION validar_orden_integridad() RETURNS TRIGGER AS $$
BEGIN
 IF EXISTS(SELECT 1 FROM Pedido p WHERE p.id_orden=NEW.id_orden AND p.fecha_solicitud>NEW.fecha_creacion) OR EXISTS(SELECT 1 FROM Adjudicacion a WHERE a.id_orden=NEW.id_orden AND a.fecha_resolucion<NEW.fecha_creacion) THEN RAISE EXCEPTION 'Las fechas de la orden contradicen sus solicitudes o adjudicación'; END IF;
 IF NEW.id_subtipo IS NOT NULL AND NOT EXISTS(SELECT 1 FROM SubtipoOrden s WHERE s.id_subtipo=NEW.id_subtipo AND s.id_tipo=NEW.id_tipo) THEN RAISE EXCEPTION 'El subtipo no pertenece al tipo'; END IF;
 RETURN NEW;
END; $$ LANGUAGE plpgsql;
-- @batch
DROP TRIGGER IF EXISTS tr_OrdenCompra_Integridad ON OrdenCompra;
CREATE TRIGGER tr_OrdenCompra_Integridad BEFORE INSERT OR UPDATE ON OrdenCompra FOR EACH ROW EXECUTE FUNCTION validar_orden_integridad();
